clc;
close all;
clear all;
fs=200;
f1=10;
f2=20;
f3=30;
f4=40;
f5=50;
ts=1/fs;
dt=0:ts:5;
s=(sin(2*pi*f1.*dt)+sin(2*pi*f2.*dt)+sin(2*pi*f3.*dt)+sin(2*pi*f4.*dt)+sin(2*pi*f5.*dt));
ff=fft(s);
fd=ff(1:length(ff)/2);
f=linspace(0,100,length(s)/2);
fc=12;
fn=fs/2;
w=fc/fn;
b=fir1(50,w);
fi=filter(b,1,s);
u=fft(fi);
c=u(1:length(u)/2);
subplot(221);
plot(dt,s);
title("noisy signal");
xlabel("time");
ylabel("y");
subplot(222);
plot(dt,fi);
title("filtered signal");
xlabel("time");
ylabel("y");
subplot(223);
plot(f,abs(fd));
ylabel("H(w)");
xlabel("frequency");
title("fft of noisy signal");
subplot(224);
plot(f,abs(c));
ylabel("H(w)");
xlabel("frequency");
title("fft of filtered signal");
