clc;
clear all;
close all;
L=61;
boxcar=[zeros(1,20),ones(1,21),zeros(1,20)];
hann=hanning(L)';
hamm=hamming(L)';
n=-30:30;
f=30;
fs=90;
F=f/fs;
nc=0:60;
h=sin(n.*F)./(pi.*n);
h(31)=0.34;
subplot(2,2,1);
stem(nc,h);
title("finite causal impulse response");
xlabel("n");
ylabel("h");
hannwindow=h.*hann;

[H,W]=freqz(hannwindow,1,61);
subplot(2,2,2)
plot(W,abs(H));
title("hannwindow");
xlabel("W");
ylabel("H");
hammwindow=hamm.*h;
[H1,W1]=freqz(hammwindow,1,61);
subplot(2,2,3);
plot(W1,abs(H1));
title("hammwindow");
xlabel("W1");
ylabel("H1");
rectwindow=boxcar.*h;
[H2,W2]=freqz(rectwindow,1,61);
subplot(2,2,4);
plot(W1,abs(H2));
title("rectangular");
xlabel("W1");
ylabel("H1");